version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receipts-parser-app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres:5432/${DATABASE_NAME}
      AZURE_COGNITIVE_SERVICES_ENDPOINT: ${AZURE_COGNITIVE_SERVICES_ENDPOINT}
      AZURE_COGNITIVE_SERVICES_API_KEY: ${AZURE_COGNITIVE_SERVICES_API_KEY}
      API_URL: "http://localhost:3000/api"

  postgres:
    image: postgres
    container_name: receipts-parser-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432

volumes:
  postgres:
    name: receipts-parser-data
