version: "3.8"

services:
  postgres:
    image: postgres
    container_name: receipts-parser-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432

volumes:
  postgres:
    name: receipts-parser-data
